### ISSUE TITLE
希望寻求一些建议

### ISSUE THREAD

**Issue by SJLNNU** [emptysoal/keypoint-resnet50#2]
您好，我使用您的代码希望用于交通标志牌的四个角点的确定中，但是我发现效果一直不理想。训练集大约是700+，测试集合66张。采用的标注形式和您一致。示例图像如下：
![Snipaste_2023-07-26_11-12-25](https://github.com/emptysoal/keypoint-resnet50/assets/31751988/d2dcb621-f14f-4983-920d-825b23483604)
能给我一些提升精度的建议吗？

**Comment by emptysoal** [comment]
你好，我平时不怎么看邮件，所以才看到这个issue。

首先，这个项目可以使用 resnet，也可以使用 hrnet，我在项目代码中仅开放了 resnet，你可以把 train.py 中第 121 行注释打开启用 hrnet，如下图：
![Dingtalk_20240621133554](https://github.com/emptysoal/keypoint-resnet50/assets/57931586/fa254f51-82f1-4390-af42-4dcdc02c9481)
hrnet的效果肯定是更好的

其次，我在dataset.py当中仅使用了简单的调整颜色作为图像的预处理，你可以增加一些预处理来提高泛化性

目前我想到的就这些，预祝你最终能有个好的预测结果，也感谢对我项目的使用

**Comment by SJLNNU** [comment]
> 你好，我平时不怎么看邮件，所以才看到这个issue。
> 
> 首先，这个项目可以使用 resnet，也可以使用 hrnet，我在项目代码中仅开放了 resnet，你可以把 train.py 中第 121 行注释打开启用 hrnet，如下图： ![Dingtalk_20240621133554](https://private-user-images.githubusercontent.com/57931586/341653168-fa254f51-82f1-4390-af42-4dcdc02c9481.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODUxMTMsIm5iZiI6MTcxOTI4NDgxMywicGF0aCI6Ii81NzkzMTU4Ni8zNDE2NTMxNjgtZmEyNTRmNTEtODJmMS00MzkwLWFmNDItNGRjZGMwMmM5NDgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDAzMDY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDU3M2EyZWEwOTdiODYwYWIzYzFlYzRmZDU4NDYyNDhjMWNhODMzZjM4ZTZjZTAyNTE2M2FlZTE4MjA4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SaCea5zVR2JYfquV7cV1ar8rHy9WCzE6daIAnO6yr1E) hrnet的效果肯定是更好的
> 
> 其次，我在dataset.py当中仅使用了简单的调整颜色作为图像的预处理，你可以增加一些预处理来提高泛化性
> 
> 目前我想到的就这些，预祝你最终能有个好的预测结果，也感谢对我项目的使用

感谢您的回复，我得到的效果相比之前好很多。
我已经关闭这个Issue。
